version: '3.1'
services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:latest
    environment:
      ORACLE_PWD: "secret"
    ports:
      - "1521:1521"   # SQL*Net
      - "5500:5500"   # EM Express
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./create_schema.sql:/opt/oracle/scripts/startup/create_schema.sql:ro
volumes:
  oracle_data:
